# Generated by Django 2.2.5 on 2019-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
